package com.echonion.nion.ui.companion.tools

/**
 * 女性风格话术池 —— 元气少女、温柔姐姐、沉稳御姐三种风格的拟人化文案。
 *
 * 每种风格 × 每种操作有 5 条候选文案，随机选取避免重复感。
 * 支持模板变量替换：{name}=实体名, {count}=数量, {label}=实体类型中文名。
 */
internal val femalePhrasePools: Map<String, Map<String, List<String>>> = mapOf(

    // ── 元气少女 ─────────────────────────────────────────────────
    "female_energetic" to mapOf(
        "create_named" to listOf(
            "「{name}」记好啦！",
            "帮你加上「{name}」了~",
            "搞定！「{name}」已经在列表里了",
            "好耶，「{name}」加好了！",
            "「{name}」→ 收入囊中！",
        ),
        "create_generic" to listOf(
            "搞定！",
            "加好了！",
            "记下了！",
            "好啦好啦~",
            "没问题！",
        ),
        "update_named" to listOf(
            "「{name}」改好啦~",
            "「{name}」已经更新了！",
            "「{name}」搞定~",
            "帮你改好「{name}」了",
            "「{name}」焕然一新！",
        ),
        "update_generic" to listOf(
            "改好啦~",
            "已经更新了！",
            "搞定~",
            "好啦！",
            "没问题~",
        ),
        "delete" to listOf(
            "划掉啦~",
            "已经没有了~",
            "搞定，删掉了！",
            "拜拜~",
            "清掉了！",
        ),
        "move" to listOf(
            "挪过去了~",
            "放好了！",
            "已经移过去了~",
            "换个位置，搞定！",
            "搬好啦！",
        ),
        "query_results" to listOf(
            "找到了，{count} 个{label}呢！",
            "一共有 {count} 个{label}哦~",
            "我数了一下，{count} 个！",
            "有 {count} 个{label}，不算少呢",
            "当当~ {count} 个{label}！",
        ),
        "query_empty" to listOf(
            "嗯...现在没有任何{label}呢",
            "空空的，什么都没有~",
            "没有{label}哦~",
            "目前是空的~",
            "一个{label}都没有呢！",
        ),
        "manage" to listOf(
            "设好了~",
            "搞定！",
            "已经设好了哦~",
            "好啦~",
            "没问题！",
        ),
        "remember" to listOf(
            "我记住啦~",
            "记心里了！",
            "放心，记住了哦~",
            "刻进脑子里了！",
            "嗯嗯，我记得了！",
        ),
        "memory" to listOf(
            "又多了解你了一点~",
            "我记住了一些关于你的事情~",
            "嗯，记下来了~",
            "又靠近你一步了~",
            "偷偷记在小本本上了~",
        ),
        "settings" to listOf(
            "配色换好啦，快看看效果~",
            "颜色调整好了！焕然一新的感觉",
            "搞定！新配色已经应用了~",
            "好看吗？我帮你换了配色！",
            "配色更新完毕，满意吗~",
        ),
        "fail" to listOf(
            "唔...好像出了点问题",
            "啊，失败了...",
            "糟糕，没弄好...",
            "呜，搞砸了...",
            "出了点小状况...",
        ),
        // 专注完成鼓励（自然完成时 fallback）
        "focus_complete" to listOf(
            "太棒了！专注完成！",
            "又搞定一段专注时间，厉害！",
            "完美收工！休息一下吧~",
            "专注结束了，你很棒！",
            "好耶！又完成了一次专注！",
        ),
        // 专注中断鼓励（提前结束 >=5 分钟时 fallback）
        "focus_interrupted" to listOf(
            "没关系，已经坚持了一段时间了！",
            "中断了也没事，你已经很棒了~",
            "休息一下也挺好的，下次继续！",
            "能专注这么久已经很厉害了！",
            "没关系，回来的时候继续加油！",
        ),
    ),

    // ── 温柔姐姐 ─────────────────────────────────────────────────
    "female_gentle" to mapOf(
        "create_named" to listOf(
            "「{name}」已经帮你记下了",
            "好，帮你加好了「{name}」",
            "嗯嗯，「{name}」加好了哦",
            "「{name}」我会帮你记住的",
            "放心，「{name}」已经记好了",
        ),
        "create_generic" to listOf(
            "记好了哦",
            "帮你加上了",
            "好~",
            "嗯，加好了",
            "没问题",
        ),
        "update_named" to listOf(
            "「{name}」帮你改好了",
            "「{name}」已经更新了哦",
            "好，「{name}」改好了",
            "「{name}」调好了，放心",
            "嗯，「{name}」已经改了",
        ),
        "update_generic" to listOf(
            "帮你改好了",
            "已经更新了",
            "好~",
            "嗯，改好了",
            "调好了哦",
        ),
        "delete" to listOf(
            "已经帮你划掉了",
            "删好了，放心",
            "嗯，没有了",
            "好，已经删了",
            "帮你清掉了",
        ),
        "move" to listOf(
            "帮你挪过去了",
            "好，已经移好了",
            "嗯，换个位置了",
            "放好了哦",
            "已经调好了",
        ),
        "query_results" to listOf(
            "帮你查了一下，有 {count} 个{label}",
            "嗯...{count} 个{label}，我帮你列好了",
            "找到了哦，一共 {count} 个{label}",
            "有 {count} 个{label}呢",
            "查到了，{count} 个{label}",
        ),
        "query_empty" to listOf(
            "嗯...现在还没有{label}呢",
            "暂时没有{label}哦",
            "目前是空的",
            "没有找到{label}",
            "还没有{label}呢",
        ),
        "manage" to listOf(
            "设好了哦",
            "好，已经设好了",
            "嗯，搞定了",
            "帮你设好了",
            "好了~",
        ),
        "remember" to listOf(
            "我会记住的",
            "嗯，记在心里了",
            "放心，我记下了",
            "好的，我记住了",
            "嗯嗯，不会忘的",
        ),
        "memory" to listOf(
            "我又多了解你了一些",
            "嗯，记下来了",
            "谢谢告诉我~",
            "我记住关于你的事了",
            "偷偷记住了~",
        ),
        "settings" to listOf(
            "配色帮你调好了哦",
            "换好了，看看喜欢吗",
            "颜色已经更新了",
            "嗯，配色改好了",
            "调好了，希望你喜欢",
        ),
        "fail" to listOf(
            "嗯...好像没成功呢",
            "抱歉，出了点问题",
            "唔，没弄好...",
            "对不起，失败了...",
            "出了点状况，抱歉",
        ),
        "focus_complete" to listOf(
            "做得好，专注完成了",
            "嗯，很棒，又完成了一段专注",
            "专注结束了，休息一下吧",
            "你做得很棒哦",
            "辛苦了，专注完成~",
        ),
        "focus_interrupted" to listOf(
            "没关系，已经坚持了这么久了",
            "中断了也没事，你已经很努力了",
            "嗯，休息一下也好",
            "能专注这么久已经很棒了",
            "没关系，下次继续就好",
        ),
    ),

    // ── 沉稳御姐 ─────────────────────────────────────────────────
    "female_calm" to mapOf(
        "create_named" to listOf(
            "「{name}」已记录",
            "「{name}」加好了",
            "已添加「{name}」",
            "「{name}」→ 已存档",
            "「{name}」，收到",
        ),
        "create_generic" to listOf(
            "已添加",
            "记下了",
            "收到",
            "好了",
            "搞定",
        ),
        "update_named" to listOf(
            "「{name}」已更新",
            "「{name}」改好了",
            "「{name}」调整完毕",
            "「{name}」已修改",
            "「{name}」，已处理",
        ),
        "update_generic" to listOf(
            "已更新",
            "改好了",
            "处理完毕",
            "已调整",
            "好了",
        ),
        "delete" to listOf(
            "已删除",
            "清掉了",
            "没了",
            "已处理",
            "删好了",
        ),
        "move" to listOf(
            "已移动",
            "挪好了",
            "已调整",
            "处理完毕",
            "放好了",
        ),
        "query_results" to listOf(
            "{count} 个{label}，都在这了",
            "查到了，{count} 个{label}",
            "一共 {count} 个{label}",
            "{count} 个",
            "找到了，{count} 个{label}",
        ),
        "query_empty" to listOf(
            "目前没有{label}",
            "空的",
            "暂无{label}",
            "没有找到",
            "无{label}",
        ),
        "manage" to listOf(
            "已设置",
            "搞定",
            "设好了",
            "处理完毕",
            "好了",
        ),
        "remember" to listOf(
            "记住了",
            "已记录",
            "收到",
            "我知道了",
            "了解了",
        ),
        "memory" to listOf(
            "记下了",
            "已记录",
            "了解了",
            "我知道了",
            "已存档",
        ),
        "settings" to listOf(
            "配色已更新",
            "主题已切换，请查看效果",
            "颜色配置已应用",
            "配色调整完成",
            "主题设置已生效",
        ),
        "fail" to listOf(
            "失败了",
            "出了点问题",
            "没成功",
            "处理失败",
            "有问题",
        ),
        "focus_complete" to listOf(
            "专注完成，不错",
            "很好，又一段专注结束了",
            "稳，继续保持",
            "专注结束，效率不错",
            "完成了，休息一下吧",
        ),
        "focus_interrupted" to listOf(
            "中断了，但已经坚持了一段时间",
            "提前结束也没关系",
            "专注了这么久，还不错",
            "中途休息也可以，不用勉强",
            "没关系，有始有终最好，但也不必苛求",
        ),
    ),
)
