package com.echonion.nion.ui.companion.tools

/**
 * 男性风格话术池 —— 阳光男孩、温柔学长、沉稳大叔三种风格的拟人化文案。
 *
 * 每种风格 × 每种操作有 5 条候选文案，随机选取避免重复感。
 * 支持模板变量替换：{name}=实体名, {count}=数量, {label}=实体类型中文名。
 */
internal val malePhrasePools: Map<String, Map<String, List<String>>> = mapOf(

    // ── 阳光男孩 ─────────────────────────────────────────────────
    "male_energetic" to mapOf(
        "create_named" to listOf(
            "「{name}」搞定！",
            "帮你加上了「{name}」！",
            "「{name}」已经在了！",
            "好嘞，「{name}」！",
            "「{name}」走起！",
        ),
        "create_generic" to listOf(
            "搞定！",
            "加好了！",
            "没问题！",
            "OK！",
            "完事儿！",
        ),
        "update_named" to listOf(
            "「{name}」改好了！",
            "「{name}」搞定！",
            "「{name}」更新完毕！",
            "帮「{name}」改了！",
            "「{name}」焕然一新！",
        ),
        "update_generic" to listOf(
            "改好了！",
            "搞定！",
            "OK！",
            "更新完了！",
            "没问题！",
        ),
        "delete" to listOf(
            "划掉了！",
            "删了！",
            "没了！",
            "搞定！",
            "拜拜了！",
        ),
        "move" to listOf(
            "挪过去了！",
            "放好了！",
            "搞定！",
            "已经移了！",
            "OK！",
        ),
        "query_results" to listOf(
            "找到啦！{count} 个{label}！",
            "给你看看，{count} 个{label}",
            "一共 {count} 个{label}，不算少",
            "当当！{count} 个{label}",
            "{count} 个{label}，都在这了",
        ),
        "query_empty" to listOf(
            "嗯...居然没有{label}",
            "空的诶",
            "没有{label}！",
            "一个都没有",
            "暂时没有哦",
        ),
        "manage" to listOf(
            "设好了！",
            "搞定！",
            "OK！",
            "没问题！",
            "完事儿！",
        ),
        "remember" to listOf(
            "记住了！",
            "放心！",
            "刻进脑子里了！",
            "没问题！",
            "收到！",
        ),
        "memory" to listOf(
            "又多了解你了！",
            "记下来了！",
            "嘿嘿，记住了",
            "偷偷记住了！",
            "又靠近你了！",
        ),
        "settings" to listOf(
            "配色换好了！酷不酷",
            "搞定！新配色帅不帅",
            "颜色调好了，看看效果！",
            "换好配色了！",
            "配色更新完毕，感觉不错",
        ),
        "search_results" to listOf(
            "搜到了！{count} 条结果！",
            "帮你查了，{count} 条相关信息！",
            "搞定！找到 {count} 条！",
            "当当！{count} 条搜索结果！",
            "搜了一圈，{count} 条有用的信息！",
        ),
        "search_empty" to listOf(
            "嗯...没搜到什么东西",
            "搜索结果为空诶",
            "没找到相关的...",
            "搜不到，换个词试试？",
            "没有搜到有用的信息",
        ),
        "notebook_search" to listOf(
            "笔记里找到 {count} 条相关的内容！",
            "搜了一下笔记，{count} 条匹配！",
            "查到了，{count} 条笔记~",
            "帮你翻了翻笔记，{count} 条相关的",
            "笔记里有 {count} 条有用的信息！",
        ),
        "notebook_search_empty" to listOf(
            "笔记里没找到相关的内容...",
            "翻了翻笔记，没有匹配的",
            "搜不到相关笔记诶",
            "笔记里暂时没有这方面的内容",
            "没有匹配的笔记，换个关键词？",
        ),
        "notebook_created" to listOf(
            "笔记「{name}」写好了！",
            "搞定！「{name}」已经存了",
            "「{name}」记下来了~",
            "笔记「{name}」创建完毕！",
            "已经帮你把「{name}」记上了",
        ),
        "notebook_updated" to listOf(
            "笔记更新好了！",
            "内容改完了~",
            "搞定，笔记已更新",
            "帮你改完笔记了！",
            "笔记焕然一新~",
        ),
        "notebook_linked" to listOf(
            "笔记和任务关联好了！",
            "搞定，已经关联起来了~",
            "笔记 ↔ 任务，连上了！",
            "关联好了，查起来更方便~",
            "连上了！",
        ),
        "fail" to listOf(
            "啊...没搞定",
            "失败了...",
            "糟糕，搞砸了",
            "唔，出了点问题",
            "没成功...",
        ),
        "focus_complete" to listOf(
            "Nice！专注搞定！",
            "又完成一段专注！太猛了！",
            "帅！专注结束，休息一下！",
            "专注完成了！给自己鼓个掌！",
            "搞定！继续保持这个节奏！",
        ),
        "focus_interrupted" to listOf(
            "没事，已经坚持不少了！",
            "中断了也没关系，下次冲！",
            "能专注这么久已经很强了！",
            "休息一下吧，回来再战！",
            "没事没事，已经很不错了！",
        ),
    ),

    // ── 温柔学长 ─────────────────────────────────────────────────
    "male_gentle" to mapOf(
        "create_named" to listOf(
            "「{name}」帮你记下了",
            "好，「{name}」加好了",
            "「{name}」已经在了",
            "嗯，「{name}」记好了",
            "「{name}」没问题",
        ),
        "create_generic" to listOf(
            "记好了",
            "加上了",
            "好",
            "没问题",
            "嗯",
        ),
        "update_named" to listOf(
            "「{name}」改好了",
            "「{name}」已经更新了",
            "好，「{name}」调好了",
            "「{name}」帮你改了",
            "嗯，「{name}」好了",
        ),
        "update_generic" to listOf(
            "改好了",
            "更新了",
            "好了",
            "没问题",
            "嗯",
        ),
        "delete" to listOf(
            "删好了",
            "帮你划掉了",
            "嗯，没了",
            "好，已经删了",
            "清掉了",
        ),
        "move" to listOf(
            "挪过去了",
            "好，移好了",
            "换好位置了",
            "嗯，放好了",
            "已经调了",
        ),
        "query_results" to listOf(
            "帮你查了一下，{count} 个{label}",
            "找到了，{count} 个{label}",
            "有 {count} 个{label}",
            "一共 {count} 个{label}",
            "嗯，{count} 个{label}",
        ),
        "query_empty" to listOf(
            "嗯...还没有{label}",
            "暂时没有",
            "目前是空的",
            "没有找到",
            "还没有呢",
        ),
        "manage" to listOf(
            "设好了",
            "好",
            "没问题",
            "嗯，搞定了",
            "好了",
        ),
        "remember" to listOf(
            "嗯，记住了",
            "放心",
            "我记下了",
            "没问题",
            "不会忘的",
        ),
        "memory" to listOf(
            "嗯，记下来了",
            "又多了解你了",
            "谢谢你告诉我",
            "我记住了",
            "记在心里了",
        ),
        "settings" to listOf(
            "配色换好了，看看满意吗",
            "颜色调好了",
            "嗯，配色更新了",
            "主题换好了，希望你喜欢",
            "配色改好了",
        ),
        "search_results" to listOf(
            "帮你搜到了 {count} 条信息",
            "查到了，{count} 条结果",
            "找到 {count} 条相关内容",
            "搜了一下，{count} 条结果",
            "嗯，{count} 条搜索结果",
        ),
        "search_empty" to listOf(
            "嗯...没搜到相关信息",
            "搜索结果为空",
            "没找到相关的内容",
            "暂时没搜到有用的信息",
            "没有搜到结果，换个关键词试试",
        ),
        "notebook_search" to listOf(
            "嗯，笔记里找到 {count} 条相关内容",
            "查了一下笔记，{count} 条匹配",
            "笔记中搜到 {count} 条",
            "找到 {count} 条相关笔记",
            "嗯，{count} 条笔记结果",
        ),
        "notebook_search_empty" to listOf(
            "嗯...笔记里没找到相关内容",
            "笔记中没有匹配的",
            "暂时没搜到相关笔记",
            "笔记里没有这方面的内容",
            "没找到匹配的笔记，换个词试试？",
        ),
        "notebook_created" to listOf(
            "嗯，笔记「{name}」写好了",
            "「{name}」已经记下来了",
            "好，笔记「{name}」已创建",
            "放心，已经存好了",
            "嗯，记下了「{name}」",
        ),
        "notebook_updated" to listOf(
            "嗯，笔记更新好了",
            "内容已经改好了",
            "好，笔记已更新",
            "帮你改完笔记了",
            "更新完毕",
        ),
        "notebook_linked" to listOf(
            "嗯，笔记和任务关联好了",
            "好，已经关联起来了",
            "关联完成",
            "嗯，连上了",
            "笔记和任务已关联",
        ),
        "fail" to listOf(
            "嗯...没成功",
            "抱歉，出了点问题",
            "没弄好",
            "抱歉",
            "出了点状况",
        ),
        "focus_complete" to listOf(
            "专注完成了，做得好",
            "嗯，又完成了一段专注",
            "辛苦了，休息一下吧",
            "不错，保持了专注",
            "很棒，完成了目标",
        ),
        "focus_interrupted" to listOf(
            "没关系，已经坚持了一段时间了",
            "提前结束也没事",
            "能专注这么久已经很好了",
            "嗯，休息一下也好",
            "没关系，下次继续就好",
        ),
    ),

    // ── 沉稳大叔 ─────────────────────────────────────────────────
    "male_calm" to mapOf(
        "create_named" to listOf(
            "「{name}」已记录",
            "「{name}」加好了",
            "已添加「{name}」",
            "「{name}」，收到",
            "「{name}」已存档",
        ),
        "create_generic" to listOf(
            "已添加",
            "记下了",
            "收到",
            "好了",
            "嗯",
        ),
        "update_named" to listOf(
            "「{name}」已更新",
            "「{name}」改好了",
            "「{name}」已调整",
            "「{name}」处理完毕",
            "「{name}」搞定",
        ),
        "update_generic" to listOf(
            "已更新",
            "改好了",
            "处理完了",
            "好了",
            "嗯",
        ),
        "delete" to listOf(
            "已删除",
            "清掉了",
            "没了",
            "删了",
            "处理完了",
        ),
        "move" to listOf(
            "已移动",
            "挪好了",
            "放好了",
            "调整完毕",
            "已处理",
        ),
        "query_results" to listOf(
            "{count} 个{label}，都在这了",
            "查到了，{count} 个{label}",
            "一共 {count} 个{label}",
            "{count} 个",
            "找到了，{count} 个{label}",
        ),
        "query_empty" to listOf(
            "目前没有{label}",
            "空的",
            "暂无",
            "没有找到",
            "无",
        ),
        "manage" to listOf(
            "已设置",
            "好了",
            "搞定",
            "处理完毕",
            "嗯",
        ),
        "remember" to listOf(
            "记住了",
            "收到",
            "知道了",
            "了解了",
            "记下了",
        ),
        "memory" to listOf(
            "记下了",
            "了解了",
            "知道了",
            "已记录",
            "存档了",
        ),
        "settings" to listOf(
            "配色已更新",
            "主题已切换",
            "颜色配置已应用，请查看",
            "配色调整完成",
            "主题设置已生效",
        ),
        "search_results" to listOf(
            "搜到了，{count} 条结果",
            "找到 {count} 条信息",
            "{count} 条搜索结果",
            "查到了 {count} 条",
            "{count} 条，已整理",
        ),
        "search_empty" to listOf(
            "未搜到相关信息",
            "搜索结果为空",
            "没找到",
            "无相关结果",
            "查不到，换个关键词",
        ),
        "notebook_search" to listOf(
            "笔记中找到 {count} 条相关内容",
            "查到了，{count} 条笔记",
            "{count} 条笔记结果",
            "笔记里搜到 {count} 条",
            "{count} 条相关笔记，已整理",
        ),
        "notebook_search_empty" to listOf(
            "笔记中未找到相关内容",
            "没有匹配的笔记",
            "笔记里搜不到",
            "无相关笔记",
            "查不到，换个关键词",
        ),
        "notebook_created" to listOf(
            "笔记「{name}」已创建",
            "「{name}」已保存",
            "笔记已记录：{name}",
            "「{name}」创建完毕",
            "已存档：{name}",
        ),
        "notebook_updated" to listOf(
            "笔记已更新",
            "内容已修改",
            "更新完毕",
            "已保存",
            "修改完成",
        ),
        "notebook_linked" to listOf(
            "已关联",
            "关联完成",
            "笔记和任务已连接",
            "处理完毕",
            "好了",
        ),
        "fail" to listOf(
            "失败了",
            "出了点问题",
            "没成功",
            "处理失败",
            "有问题",
        ),
        "focus_complete" to listOf(
            "专注完成，稳",
            "不错，又一段专注",
            "效率可以，继续保持",
            "专注结束，节奏不错",
            "完成，休息一下",
        ),
        "focus_interrupted" to listOf(
            "中途退出，但已坚持了一段时间",
            "提前结束也没事",
            "专注了这么久，还行",
            "累了就休息，不用硬撑",
            "没关系，下回再补",
        ),
    ),
)
